<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(RepoRoot)src\Common.Dotnet.CsWinRT.props" />
  <Import Project="$(RepoRoot)src\Common.Dotnet.AotCompatibility.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
    <NoWarn>$(NoWarn);NU1510;SA0001;SA1200;SA1201;SA1402;SA1516;SA1600;SA1633;SA1649</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(RepoRoot)src\common\AiHub\Kit.AiHub.csproj" />
  </ItemGroup>
</Project>
