namespace PowerToys
{
    namespace Interop
    {
        [default_interface] static runtimeclass Constants {
            static UInt32 VK_WIN_BOTH {get; };
            static String AppDataPath();
            static String LightSwitchToggleEvent();
            static String AwakeExitEvent();
            static String KitRunnerTerminateSettingsEvent();
            static String TogglePowerDisplayEvent();
            static String TerminatePowerDisplayEvent();
            static String RefreshPowerDisplayMonitorsEvent();
            static String SettingsUpdatedPowerDisplayEvent();
            static String HotkeyUpdatedPowerDisplayEvent();
            static String PowerDisplayToggleMessage();
            static String PowerDisplayApplyProfileMessage();
            static String PowerDisplayTerminateAppMessage();
        }
    }
}
