<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(RepoRoot)src\Common.Dotnet.CsWinRT.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier Condition="'$(Platform)' == 'x64'">win-x64</RuntimeIdentifier>
    <RuntimeIdentifier Condition="'$(Platform)' == 'ARM64'">win-arm64</RuntimeIdentifier>
    <OutputPath>$(RepoRoot)$(Platform)\$(Configuration)\tests\Localserver\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <NoWarn>$(NoWarn);SA0001;SA1200;SA1309;SA1516;SA1600;SA1633;SA1649;SA1402;CA1861;CA1305</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest" />
    <ProjectReference Include="..\LocalserverLib\LocalserverLib.csproj" />
    <ProjectReference Include="..\LocalserverWorker\LocalserverWorker.csproj" />
  </ItemGroup>
</Project>
